server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:55555/orderdb
    username: orderdbuser
    password: orderdbpassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      # properties.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true